### ISSUE TITLE
Which version of Ubuntu ?

### ISSUE THREAD

**Issue by JOduMonT** [tych0/tycho.ws#2]
Hi;

i'm using 16.04LTS
eth0 is now something like : enp0s31f6
so those command not working

> lxc profile device set default eth0 parent eth0

in this directory /etc/network/interfaces.d/
nothing exist...

it is possible to have a translation ..
do you notice other change between your demo and 16.04lts ?

**Comment by JOduMonT** [comment]
Since I try to run those command, my lxd container not working anymore
I realize your command modify the default profile :(

> lxc profile device set **default** eth0 parent eth0

it is possible to reverse the config, and/or what is the default config of this default profile ?

**Comment by tych0** [comment]
The default profile is:

```
name: default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
```

if you restore it to that, things should work. Can you show your current profile configuration and the output of `ip a`?
